"""date added

Revision ID: 0b822993e5ce
Revises: 4abd15f9d44c
Create Date: 2019-11-09 11:45:56.003977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b822993e5ce'
down_revision = '4abd15f9d44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'date')
    # ### end Alembic commands ###
